framework:
    mailer:
        dsn: "ses://%env(AWS_S3_ACCESS_ID)%:%env(AWS_S3_ACCESS_SECRET)%@default?region=%env(AWS_S3_REGION)%"
        envelope:
            sender: "contact@tarmac.center"
        headers:
            From: "Tarmac <contact@tarmac.center>"

when@dev:
    framework:
        mailer:
            envelope:
                recipient: "thibault@henry.pro"
