_translation_webui:
  resource: "@TranslationBundle/Resources/config/routing_webui.yaml"
  prefix: /_trans

_translation_profiler:
  resource: "@TranslationBundle/Resources/config/routing_symfony_profiler.yaml"
