<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;
use Doctrine\Migrations\Exception\IrreversibleMigration;

/**
 * Nettoyage des résidus laissés par Doctrine DBAL 3 / ORM 2 :
 *
 * 1. Conversion des colonnes `id` SERIAL/BIGSERIAL → GENERATED BY DEFAULT AS IDENTITY.
 *    DBAL 4 + ORM 3 (avec `identity_generation_preferences` postgres = identity)
 *    régénéraient sinon ces ALTER à chaque `make:migration`, polluant les diffs.
 *    Les valeurs existantes sont préservées et la nouvelle identité repart à MAX(id)+1.
 *
 * 2. Suppression des commentaires `(DC2Type:*_immutable)` devenus inutiles
 *    avec DBAL 4 (la conversion de type est déduite depuis les métadonnées ORM).
 *
 * Down() non implémenté : remettre des SERIAL n'a aucune valeur métier.
 */
final class Version20260527170000 extends AbstractMigration
{
    /**
     * Toutes les tables possédant une colonne `id` créée en SERIAL/BIGSERIAL.
     * Le nom de séquence implicite suit la convention <table>_id_seq.
     */
    private const ID_TABLES = [
        'activity',
        'club',
        'contribution',
        'equipment',
        'invitation',
        'membership',
        'messenger_messages',
        'plan',
        'plan_application',
        'plan_sub_task',
        'plan_task',
        'purchase',
        'reset_password_request',
        'specialisation',
        'sub_task',
        'task',
        '"user"',
    ];

    /**
     * Commentaires DC2Type à effacer.
     * Format : table => [colonnes]
     */
    private const DC2TYPE_COMMENTS = [
        'activity' => ['created_at'],
        'club' => ['created_at'],
        'contribution' => ['created_at'],
        'equipment' => ['created_at'],
        'invitation' => ['created_at', 'expires_at'],
        'membership' => ['created_at', 'joined_at'],
        'messenger_messages' => ['available_at', 'created_at', 'delivered_at'],
        'plan' => ['created_at', 'updated_at'],
        'plan_application' => ['applied_at', 'cancelled_at', 'due_at'],
        'purchase' => [
            'approved_at',
            'cancelled_at',
            'created_at',
            'delivered_at',
            'expected_delivery_date',
            'purchased_at',
            'reimbursed_at',
        ],
        'reset_password_request' => ['expires_at', 'requested_at'],
        'sub_task' => ['cancelled_at', 'created_at', 'done_at', 'inspected_at'],
        'task' => ['cancelled_at', 'created_at', 'due_at'],
        '"user"' => ['created_at'],
    ];

    public function getDescription(): string
    {
        return 'Convert SERIAL ids to IDENTITY and drop legacy DC2Type comments to stop polluting auto-generated migrations.';
    }

    public function up(Schema $schema): void
    {
        $this->abortIf(
            !$this->connection->getDatabasePlatform() instanceof \Doctrine\DBAL\Platforms\PostgreSQLPlatform,
            'Cette migration cible PostgreSQL uniquement.'
        );

        foreach (self::ID_TABLES as $quotedTable) {
            // Nom de séquence implicite : sans les guillemets éventuels de la table.
            $unquoted = trim($quotedTable, '"');
            $sequence = $unquoted . '_id_seq';

            // 1. Détache la colonne de la séquence SERIAL.
            $this->addSql(sprintf('ALTER TABLE %s ALTER COLUMN id DROP DEFAULT', $quotedTable));

            // 2. Supprime l'ancienne séquence (devenue orpheline) pour libérer le nom.
            $this->addSql(sprintf('DROP SEQUENCE IF EXISTS %s', $sequence));

            // 3. Ajoute l'IDENTITY en repartant à MAX(id)+1 pour éviter toute collision.
            //    Le RESTART WITH dynamique passe par un bloc PL/pgSQL car ALTER TABLE
            //    n'accepte pas de sous-requête pour la valeur de redémarrage.
            $this->addSql(sprintf(
                <<<'SQL'
                DO $do$
                DECLARE
                    next_val bigint;
                BEGIN
                    SELECT COALESCE(MAX(id), 0) + 1 INTO next_val FROM %s;
                    EXECUTE format(
                        'ALTER TABLE %s ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (RESTART WITH %%s)',
                        next_val
                    );
                END
                $do$;
                SQL,
                $quotedTable,
                $quotedTable
            ));
        }

        foreach (self::DC2TYPE_COMMENTS as $table => $columns) {
            foreach ($columns as $column) {
                $this->addSql(sprintf("COMMENT ON COLUMN %s.%s IS NULL", $table, $column));
            }
        }
    }

    public function down(Schema $schema): void
    {
        throw new IrreversibleMigration(
            'Le retour à SERIAL/BIGSERIAL et aux commentaires DC2Type n\'est pas supporté.'
        );
    }
}
