<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260727171451 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Ajout des anomalies : table anomaly, liaison anomaly_task et rattachement au journal d\'activité';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE anomaly (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, title VARCHAR(180) NOT NULL, description TEXT NOT NULL, photos JSON NOT NULL, impact VARCHAR(20) NOT NULL, resolution VARCHAR(20) DEFAULT NULL, resolved_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, reported_at DATE NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, club_id INT NOT NULL, equipment_id INT NOT NULL, resolved_by_id INT DEFAULT NULL, reported_by_id INT DEFAULT NULL, created_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_F9F9756361190A32 ON anomaly (club_id)');
        $this->addSql('CREATE INDEX IDX_F9F97563517FE9FE ON anomaly (equipment_id)');
        $this->addSql('CREATE INDEX IDX_F9F975636713A32B ON anomaly (resolved_by_id)');
        $this->addSql('CREATE INDEX IDX_F9F9756371CE806 ON anomaly (reported_by_id)');
        $this->addSql('CREATE INDEX IDX_F9F97563B03A8386 ON anomaly (created_by_id)');
        $this->addSql('CREATE INDEX idx_anomaly_impact ON anomaly (impact)');
        $this->addSql('CREATE INDEX idx_anomaly_resolution ON anomaly (resolution)');
        $this->addSql('CREATE INDEX idx_anomaly_reported_at ON anomaly (reported_at)');
        $this->addSql('CREATE TABLE anomaly_task (anomaly_id INT NOT NULL, task_id INT NOT NULL, PRIMARY KEY (anomaly_id, task_id))');
        $this->addSql('CREATE INDEX IDX_F243E4A6BAF977BB ON anomaly_task (anomaly_id)');
        $this->addSql('CREATE INDEX IDX_F243E4A68DB60186 ON anomaly_task (task_id)');
        $this->addSql('ALTER TABLE anomaly ADD CONSTRAINT FK_F9F9756361190A32 FOREIGN KEY (club_id) REFERENCES club (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE anomaly ADD CONSTRAINT FK_F9F97563517FE9FE FOREIGN KEY (equipment_id) REFERENCES equipment (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('ALTER TABLE anomaly ADD CONSTRAINT FK_F9F975636713A32B FOREIGN KEY (resolved_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE anomaly ADD CONSTRAINT FK_F9F9756371CE806 FOREIGN KEY (reported_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE anomaly ADD CONSTRAINT FK_F9F97563B03A8386 FOREIGN KEY (created_by_id) REFERENCES "user" (id) ON DELETE SET NULL NOT DEFERRABLE');
        $this->addSql('ALTER TABLE anomaly_task ADD CONSTRAINT FK_F243E4A6BAF977BB FOREIGN KEY (anomaly_id) REFERENCES anomaly (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE anomaly_task ADD CONSTRAINT FK_F243E4A68DB60186 FOREIGN KEY (task_id) REFERENCES task (id) ON DELETE CASCADE');
        $this->addSql('ALTER TABLE activity ADD anomaly_id INT DEFAULT NULL');
        $this->addSql('ALTER TABLE activity ADD CONSTRAINT FK_AC74095ABAF977BB FOREIGN KEY (anomaly_id) REFERENCES anomaly (id) ON DELETE CASCADE NOT DEFERRABLE');
        $this->addSql('CREATE INDEX IDX_AC74095ABAF977BB ON activity (anomaly_id)');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE anomaly DROP CONSTRAINT FK_F9F9756361190A32');
        $this->addSql('ALTER TABLE anomaly DROP CONSTRAINT FK_F9F97563517FE9FE');
        $this->addSql('ALTER TABLE anomaly DROP CONSTRAINT FK_F9F975636713A32B');
        $this->addSql('ALTER TABLE anomaly DROP CONSTRAINT FK_F9F9756371CE806');
        $this->addSql('ALTER TABLE anomaly DROP CONSTRAINT FK_F9F97563B03A8386');
        $this->addSql('ALTER TABLE anomaly_task DROP CONSTRAINT FK_F243E4A6BAF977BB');
        $this->addSql('ALTER TABLE anomaly_task DROP CONSTRAINT FK_F243E4A68DB60186');
        $this->addSql('DROP TABLE anomaly');
        $this->addSql('DROP TABLE anomaly_task');
        $this->addSql('ALTER TABLE activity DROP CONSTRAINT FK_AC74095ABAF977BB');
        $this->addSql('DROP INDEX IDX_AC74095ABAF977BB');
        $this->addSql('ALTER TABLE activity DROP anomaly_id');
    }
}
